{% set version = "1.2.0" %}

package:
    name: pykdtree
    version: {{ version }}

source:
    fn: pykdtree-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
    md5: 78ea41ed9684aff847692011466ab640

build:
    number: 0
    script:
        - export USE_OMP=1  # [linux]
        - export USE_OMP=0  # [osx]
        - set USE_OMP=0  # [win]
        - python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - msinttypes  # [win and py<35]
    run:
        - python
        - numpy x.x

test:
    imports:
        - pykdtree

about:
    home: https://pypi.python.org/pypi/pykdtree
    license: LGPL-3.0
    summary: Fast kd-tree implementation with OpenMP-enabled queries

extra:
    recipe-maintainers:
        - ocefpaf
