{% set version = "1.3.4" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: bebe5c608129f2997e88510c00010b9a78581b394924c0e3ecd131d52415165d

build:
  number: 1002
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - msinttypes  # [win and py<35]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pykdtree

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Fast kd-tree implementation with OpenMP-enabled queries'

extra:
  recipe-maintainers:
    - ocefpaf
