{% set version = "1.4.3" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: d9187930ffb8c822c52595b64948b47346694ee2a49e2702420b58f743d786f5

build:
  number: 0
  skip: true  # [py<37]
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy >=2.0.0,<3
    - numpy   1.21  # [py==310]
    - numpy   1.23  # [py>=311]
    - _openmp_mutex  # [linux]
    - cython >=3.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - _openmp_mutex  # [linux]

test:
  requires:
    - pip
  imports:
    - pykdtree
  commands:
    - pip check

about:
  home: https://github.com/storpipfugl/pykdtree
  dev_url: https://github.com/storpipfugl/pykdtree
  doc_url: https://github.com/storpipfugl/pykdtree/blob/master/README.rst
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  license_family: LGPL
  summary: Fast kd-tree implementation with OpenMP-enabled queries
  description: |
    pykdtree is a kd-tree implementation for fast nearest neighbour search in Python.
    The aim is to be the fastest implementation around for common use cases
    (low dimensions and low number of neighbours) for both tree construction and queries.



extra:
  recipe-maintainers:
    - ocefpaf
