{% set version = "1.2.2" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: 958cb731b19f10e14471947e67602876c3ab9e01246e6b9c6c5cbfd34d17141f

build:
  number: 1
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - gcc  # [linux]
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - msinttypes  # [win and py<35]
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - libgcc  # [linux]

test:
  imports:
    - pykdtree
  commands:
    - conda inspect linkages -p $PREFIX pykdtree  # [not win]
    - conda inspect objects -p $PREFIX pykdtree  # [osx]

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0
  summary: 'Fast kd-tree implementation with OpenMP-enabled queries.'

extra:
  recipe-maintainers:
    - ocefpaf
