{% set version = "1.3.1" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: 0d49d3bbfa0366dbe29176754ec86df75114a25525b530dcbbb75d3ac4c263e9

build:
  number: 0
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - gcc  # [linux]
    - numpy 1.11.*
    - msinttypes  # [win and py<35]
  run:
    - python
    - numpy >=1.11
    - libgcc  # [linux]

test:
  imports:
    - pykdtree
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Fast kd-tree implementation with OpenMP-enabled queries.'

extra:
  recipe-maintainers:
    - ocefpaf
