{% set version = "1.4.3" %}
{% set name = "pykdtree" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9187930ffb8c822c52595b64948b47346694ee2a49e2702420b58f743d786f5

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  script_env:
    - USE_OMP=1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy {{ numpy }}
    - cython >=3.1
    # - _openmp_mutex  # [linux]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - numpy
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

test:
  imports:
    - pykdtree
  requires:
    - pip
    - pytest
    - mypy
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs pykdtree.test_stub pykdtree.test_tree

about:
  home: https://github.com/storpipfugl/pykdtree
  dev_url: https://github.com/storpipfugl/pykdtree
  doc_url: https://github.com/storpipfugl/pykdtree/blob/master/README.rst
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  license_family: LGPL
  summary: Fast kd-tree implementation with OpenMP-enabled queries
  description: |
    pykdtree is a kd-tree implementation for fast nearest neighbour search in Python.
    The aim is to be the fastest implementation around for common use cases
    (low dimensions and low number of neighbours) for both tree construction and queries.

extra:
  recipe-maintainers:
    - ocefpaf
