{% set version = "1.3.6" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: 780b693d0555b857d7aab31e35d4293bf4ebdb9dec7a45ba4bb23b4400f626dc

build:
  number: 0
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - msinttypes       # [win and py<35]
    - _openmp_mutex    # [linux and aarch64]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - _openmp_mutex    # [linux and aarch64]

test:
  imports:
    - pykdtree

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Fast kd-tree implementation with OpenMP-enabled queries'

extra:
  recipe-maintainers:
    - ocefpaf
