travis:
  secure:
    BINSTAR_TOKEN: lIb9u/ogRBttNy93fF8Zlz2AMWNHy8qxi5NnzIl9zCSx3P8y+li0/kL6+uxJu0bSd5q2IyDcnBCdW6pPpqeXkDbC4WbpnIwOgzN/ARZQ5QXt4D2eWjDbBtaIr5AakkD2jk6gwPyLA9oZFnpkOBtulmlF+YNJNcZ17+fRl3SoMUnchSeNesqAeRdzDCu1v36rgNjDQCD2K0mneIhm/1UTxMco2+h9Fpkg9N8WYs7reaMuv8lJw1ngdmTDC8A2m+jnJxs9x890bVr1+eT2CmZl1ArSq6YRsq8xvLPxtfXBm9rk+4HkBsK9mkHwYq2+VM91PROtP6JldHu5jlEHhVE2NBteNN8l9MHO/OC3pmNQuAXkU6SZPS+umv26YrxhBqg968EmVgFmMGat5os1wbidwRFrVwy9kwnfx9oh/4n8nTtg/5IR0vswK78lnCoP71QtWzuWYwl2yn3vj/6RDBHSOu37WaZRcUpJXCdVRp5g/P7Nnv+H1rqMaH0L3gyR08VQKRYuDFACFbmWNJgL3DJM/sigTmfyFQuPAoN9rhjBpvCeDlSDVm/h4wIIFp2ORKjLB4eqJSzKMxrVlhPx5Z5OAytrWWhWGSALRiBbDUb/aLWIZ+T77Z9TMvZI/tDyVc5OHOE4q/+ctWVd+UBk3sh97smtOiPUI5+8NlFDFSeYARI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
