travis:
  secure:
    BINSTAR_TOKEN: fLOktd+1N5CrrTb0C7Y/cYCdQO3mD93zqtZUw3iTKCmp8H1JFpGNOiBSDvBIJ7oEjpy1k4EfCgdqBts1okPEIY19CiHSbAVKR/w2OwLm/jK5OCqIa+eq0PTcTf67zl8WEJx0hlWUZcE1vzviVpIRPZVz0SzRcL1ZA0i4pMRDAwacO3UVQq07kkFBx0hH4phxp/mwEsumnj+TAMhK9tV6dadSOJf8umoxv2suwoVN3pMzP0B0zuWwxlIKY7jbq5bukQGuYgjxVUZTEXBxYrMb0MAP1tnd4WnBXt6pmi3/I5b8On/wQ5Z8MmWufbmgnzNzjYGo+di5dKIEOktSWuR0RxdnExnL3E5FsLPY9Ie5tLL7FrU/GaZ0vBeSOeubY5Tepf1/0OQSN5BSlPiodW6sNdDVYeFZhJ69EbOItetWdYpOEcynwbDr8YD2LBa4PbNzY82G7kJ0qRPJvIICFvn/Xd1IUCZRs4tn521kOSE/SLqZt3MC3DhNS7mux+9LipZitpajKz1HNOGDyA+q4OtAU6AXrPbv51s8/1JtvhwANl9cZESeRnca2ptJ1kE9Jx2sE8LXeQuHwOPGYvzM6jZaWxzHYid1DdUoZIRitUhseFXmESDf0vl5BPUL7m+T7Xw/jY2T+ZWWyx46zFlFm1g0Kkscx8HEH4cteSrYnQqEDGg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
